"""
label_map.py — Label mappings for the collapsed base-letter class scheme.

WHY THE COLLAPSE:
    HMBD ships 115 classes: every letter in up to four positional forms
    (e.g. Ha_Start, Ha_Middle, Ha_End, Ha_Isolated) plus digits. For a demo
    where the user draws ONE isolated character, those four forms are nearly
    indistinguishable — the model was being asked an impossible question, and
    that ambiguity dominated its errors.

    Collapsing all positional forms of a letter into ONE base class:
      - removes that impossible distinction,
      - roughly quadruples the samples per class (4 forms merged),
      - makes predictions intuitive ("Baa" instead of "Baa_Middle").

    Result: 115 original classes -> 46 base classes (28-ish letters,
    10 digits, and several hamza/ligature variants).

    Class 24 in the original mapping was the junk ".ipynb_checkpoints"
    folder and is excluded entirely.
"""

# Original HMBD label -> collapsed base-letter label (0..45).
# Generated by stripping _Start/_Middle/_End/_Isolated suffixes and grouping
# by the remaining base name. Class 24 (junk) is absent by design.
OLD_TO_BASE = {
    0: 31, 1: 12, 2: 21, 3: 40, 4: 22, 5: 28, 6: 33, 7: 6, 8: 11, 9: 32,
    10: 24, 11: 3, 12: 31, 13: 11, 14: 0, 15: 28, 16: 14, 17: 33, 18: 31,
    19: 42, 20: 40, 21: 36, 22: 4, 23: 41, 25: 2, 26: 24, 27: 20, 28: 17,
    29: 3, 30: 30, 31: 11, 32: 7, 33: 30, 34: 5, 35: 2, 36: 24, 37: 35,
    38: 42, 39: 1, 40: 45, 41: 16, 42: 27, 43: 33, 44: 8, 45: 13, 46: 1,
    47: 17, 48: 13, 49: 41, 50: 26, 51: 28, 52: 15, 53: 38, 54: 24, 55: 5,
    56: 26, 57: 28, 58: 34, 59: 13, 60: 10, 61: 29, 62: 21, 63: 12, 64: 17,
    65: 35, 66: 16, 67: 9, 68: 18, 69: 14, 70: 4, 71: 0, 72: 16, 73: 0,
    74: 43, 75: 26, 76: 39, 77: 19, 78: 31, 79: 6, 80: 43, 81: 16, 82: 38,
    83: 5, 84: 18, 85: 27, 86: 22, 87: 5, 88: 34, 89: 4, 90: 30, 91: 37,
    92: 35, 93: 18, 94: 20, 95: 30, 96: 18, 97: 13, 98: 8, 99: 19, 100: 40,
    101: 22, 102: 33, 103: 44, 104: 45, 105: 26, 106: 41, 107: 23, 108: 35,
    109: 0, 110: 25, 111: 8, 112: 4, 113: 12, 114: 8,
}

# Collapsed label -> human-readable base-letter name.
BASE_NAMES = {
    0: "Ain", 1: "Alf", 2: "Alf_Hamza_Above", 3: "Alf_Hamza_Under",
    4: "Baa", 5: "Daad", 6: "Dal", 7: "Eight", 8: "Faa", 9: "Five",
    10: "Four", 11: "Gem", 12: "Gen", 13: "Ha", 14: "Haa", 15: "Hamza",
    16: "Kaf", 17: "Khaa", 18: "Lam", 19: "Lam_Alf", 20: "Lam_Alf_Hamza",
    21: "Lam_Alf_Mad", 22: "Mem", 23: "Nine", 24: "Non", 25: "One",
    26: "Qaf", 27: "Raa", 28: "Saad", 29: "Seven", 30: "Shen", 31: "Sin",
    32: "Six", 33: "Taa", 34: "Tah", 35: "Thaa", 36: "Three", 37: "Two",
    38: "Waw", 39: "Waw_Hamza", 40: "Yaa", 41: "Yaa_Dot", 42: "Zah",
    43: "Zal", 44: "Zero", 45: "Zin",
}

NUM_BASE_CLASSES = len(BASE_NAMES)   # 46


def name_for(class_id):
    """Return the readable base-letter name for a collapsed class id."""
    return BASE_NAMES.get(class_id, f"Class {class_id}")


# --- AHCD merge mapping ----------------------------------------------------
# AHCD (Arabic Handwritten Characters Dataset) labels run 1..28 in standard
# Arabic alphabet order. Verified by rendering samples: labels 2/3/4 show
# one/two/three dots (beh/teh/theh), confirming the ordering.
# This maps each AHCD label to the matching collapsed base-class id above.
AHCD_TO_BASE = {
    1: 1,    # alef  -> Alf
    2: 4,    # beh   -> Baa
    3: 33,   # teh   -> Taa
    4: 35,   # theh  -> Thaa
    5: 11,   # jeem  -> Gem
    6: 13,   # hah   -> Ha
    7: 17,   # khah  -> Khaa
    8: 6,    # dal   -> Dal
    9: 43,   # thal  -> Zal
    10: 27,  # reh   -> Raa
    11: 45,  # zain  -> Zin
    12: 31,  # seen  -> Sin
    13: 30,  # sheen -> Shen
    14: 28,  # sad   -> Saad
    15: 5,   # dad   -> Daad
    16: 34,  # tah   -> Tah
    17: 42,  # zah   -> Zah
    18: 0,   # ain   -> Ain
    19: 12,  # ghain -> Gen
    20: 8,   # feh   -> Faa
    21: 26,  # qaf   -> Qaf
    22: 16,  # kaf   -> Kaf
    23: 18,  # lam   -> Lam
    24: 22,  # meem  -> Mem
    25: 24,  # noon  -> Non
    26: 14,  # heh   -> Haa
    27: 38,  # waw   -> Waw
    28: 40,  # yeh   -> Yaa
}
