"""
label_map.py — Class-id -> letter-name lookup.

Names were generated by build_dataset.py from the ORIGINAL HMBD folder names
(alphabetical, positional suffixes stripped), replacing the dataset's shipped
label_mapping.csv which was verified corrupt.

They are hardcoded here rather than read from data/hmbd_cache.npz so that
inference works in deployment, where the data directory is not present.
If build_dataset.py is ever re-run with different classes, regenerate this list
from its printed output.
"""

BASE_NAMES = {
    0: "Ain", 1: "Alf", 2: "Alf_Hamza_Above", 3: "Alf_Hamza_Under",
    4: "Baa", 5: "Daad", 6: "Dal", 7: "Eight", 8: "Faa", 9: "Five",
    10: "Four", 11: "Gem", 12: "Gen", 13: "Ha", 14: "Haa", 15: "Hamza",
    16: "Kaf", 17: "Khaa", 18: "Lam", 19: "Lam_Alf", 20: "Lam_Alf_Hamza",
    21: "Lam_Alf_Mad", 22: "Mem", 23: "Nine", 24: "Non", 25: "One",
    26: "Qaf", 27: "Raa", 28: "Saad", 29: "Seven", 30: "Shen", 31: "Sin",
    32: "Six", 33: "Taa", 34: "Tah", 35: "Thaa", 36: "Three", 37: "Two",
    38: "Waw", 39: "Waw_Hamza", 40: "Yaa", 41: "Yaa_Dot", 42: "Zah",
    43: "Zal", 44: "Zero", 45: "Zin",
}


def name_for(class_id):
    """Return the letter name for a class id (falls back to 'Class N')."""
    return BASE_NAMES.get(class_id, f"Class {class_id}")


def num_classes():
    """Number of base classes."""
    return len(BASE_NAMES)
